name: Enforce PR label

#####
# This workflow is triggered by pull_request_target event.
# Never checkout the PR and run ANY local code on it.
#####

on: # zizmor: ignore[dangerous-triggers] safe label enforcement; no checkout or code execution
  pull_request_target:
    types: [labeled, unlabeled, opened, edited, synchronize]
jobs:
  enforce-label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: enforce-triage-label
        uses: jupyterlab/maintainer-tools/.github/actions/enforce-label@b48fcdb87e70c45789abd80d4042b06641e47b46 # v1
