# https://github.com/marketplace/actions/labeler
name: "Pull Request Labeler"

#####
# This workflow is triggered by pull_request_target event.
# Never checkout the PR and run ANY local code on it.
#####

on:
- pull_request_target

permissions:
  pull-requests: write

jobs:
  triage:
    name: Update PR Labels
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v6
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true
