# Performs static analysis in GitHub actions with https://github.com/zizmorcore/zizmor
name: GitHub Actions Security Analysis with zizmor 🌈

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

permissions: {}

jobs:
  zizmor:
    name: zizmor pinned via PyPI
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required for upload-sarif (used by zizmor-action) to upload SARIF files.
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2

      - name: Run zizmor 🌈
        # Check zizmor version is aligned with the one in .pre-commit-config.yaml
        run: uvx zizmor@1.25.2 --format=sarif . > results.sarif
        # Note: we are not passing GitHub token here, so it runs in offline mode;
        # online mode is known to exhaust Github rate limits due to extensive
        # GitHub API calls, see https://github.com/zizmorcore/zizmor/issues/278 and
        # https://grafana.com/blog/how-to-detect-vulnerable-github-actions-at-scale-with-zizmor/
        # This means that some checks like imposter-commits and ref-confusion will not run.

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@7188fc363630916deb702c7fdcf4e481b751f97a # v4.37.1
        with:
          sarif_file: results.sarif
          category: zizmor
